# Generated by Django 3.2.6 on 2021-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
